### PR TITLE
Added option to randomize all comments and posts.

### PR DESCRIPTION
**Pull request by R-Dson**
Saw some people on Reddit requesting this feature since comments might be restored. Replacing the comments with randomized strings might help with this.

### CODE REVIEW

**Comment by karan51ngh** [comment]
Hey @R-Dson there are merge conflicts present.
- After you forked the Repo, I had pushed a [commit](https://github.com/JosemyDuarte/reddit-cleaner/commit/d9274a88f61742604a42db7bef26a8c360b2142c) to combine all the delete functions into 1 file called delete.py.
- Also regarding the randomization, yesterday I have added a method to **ENCRYPT** the comments using **SHA-256** algorithm before deletion.
- I have also added a feature that will help people to **LOG** their comments/posts before deletion.
- So the changes you pushed aren't going to be compatible.

However if you  are still open to contributing to the project I liked your idea of allowing users to **ONLY** randomize and not delete. 

So if you'd like to work on this feature, can you make changes to the **latest version** of the Repo, such that users get an Option to: - Either **ONLY** Encrypt the comments, OR **ENCRYPT and DELETE**. Feel free to ask any questions that you might have.

**Comment by R-Dson** [comment]
Thanks for commenting and making the changes. I'll close this for now since that is the easiest, and reopen or make a new pull request later if needed.

**Comment by R-Dson** [comment]
Didn't take long, I hope these changes are better.

**Review by karan51ngh — APPROVED** [review]
Made a few changes.
Changed the word Randomize to Encrypt.
Added some logic to the menu.

**Comment by R-Dson** [comment]
Nice, I realised I forgot to change some things but you fixed that. Cheers.

**Comment by karan51ngh** [comment]
Yup, thanks for the contributions though!

**Pull request merged**
